mapa1 = [

"pppppppppppppppppppppppppppppppppppppppppp",
"pttttttttt         ssss          ttttttttp",
"ptttttttt          ssss           tttttttp",
"pttttttt           ssss            ttttttp",
"ptttttt            ssss             tttttp",
"pttttt             ssss              ttttp",
"ptttt              ssss               tttp",
"pttt               ssss                ttp",
"ptt                ssss                 tp",
"pssssssssssssssssssssssssssssssssssssssssp",
"pssssssssssssssssssssssssssssssssssssssssp",
"pt                 ssss                 tp",
"ptt                ssss                ttp",
"pttt               ssss               tttp",
"ptttt              ssss              ttttp",
"pttttt             ssss             tttttp",
"ptttttt            ssss            ttttttp",
"pttttttt           ssss           tttttttp",
"ptttttttt          ssss          ttttttttp",
"pppppppppppppppppppppppppppppppppppppppppp",
]

mapaobj = [
"                    d                     ",
"          a                               ",
"       a                                  ",
"         a                                ",
"                                          ",
"         a                       a        ",
"     a                          a         ",
"                               a a        ",
"                                          ",
"                                          ",
"                                          ",
"                                          ",
"      a                   a               ",
"                                          ",
"            a                  a          ",
"                           a              ",
"         a                                ",
"                                          ",
"            a                 a           ",
"                    d                     ",
"                                          ",
]
